[package]
name = "f1-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
lazy_static = "1.4"
ureq = "2.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "2.3"
void = "1.0"
